### ISSUE TITLE
Updates for Picom?

### ISSUE THREAD

**Issue by Akorn27** [ZMASLO/dotfiles#1]
**lol because i can't recreate your blur**

**Comment by yoge67855** [comment]
yeah me too(ja tez)

**Comment by Akorn27** [comment]
musisz używać picom tryone.

**Comment by yoge67855** [comment]
install picom tryone git and type: picom --blur-method dual_kawase --experimental-backends --backend glx and itll work (do not use config)

**Comment by yoge67855** [comment]
czyli zainstaluj picom tryone git i wpisz: picom --blur-method dual_kawase --experimental-backends --backend glx     i to zadziala (nie uzywaj pliku konfiguracyjnego)

**Comment by Akorn27** [comment]
Tak to działa. Z plikiem, to nadpisuje ustawienia pliku.

**Comment by Akorn27** [comment]
Yes this works. With file, it just overrides settings of the files to specified.
